### ISSUE TITLE
맞춤 검색 그래프 이슈

### ISSUE THREAD

**Issue by jwmoon-penta** [MECTrace/TrackingService#5]
맞춤 검색에서 
device id로 검색시 그래프에 관련된 이슈입니다.

여러 data id가 겹쳐져 각 edge들간의 선 표현이 어렵습니다.

이 이슈는 device 뿐만 아니라 edge도 마찬가지로 보입니다.

**Comment by MEC-Tracing** [comment]
![image](https://user-images.githubusercontent.com/67618853/99494726-ddfb0600-29b4-11eb-97ef-116757e0a9c2.png)

다음 그림과 같이 수정해주세요
