### ISSUE TITLE
맞춤 검색 그래프 이슈 (#2)

### ISSUE THREAD

**Issue by BANDI-Plan** [MECTrace/TrackingService#6]
해당 문제는 Edge ID를 비워두고 Device ID만 넣어서 검색 할 경우 발생할 수 있는 이슈이다.

Device ID만 사용하여 조건검색을 수행할 경우 그래프개 복잡해지는 이슈가 발생한다.
예를 들어서 하나의 Device는 다수의 Edge Node에 서로 다른 Data ID를 가지는 Data를 송신한다. 이후 각 Edge Node는 그 데이터를 주변 Edge Node에 분산을 하게 되는데, 이 과정에서 그래프가 복잡해지는 이슈가 발생한다.

해당 이슈의 해결방안으로 Edge ID와 Device ID가 입력되었을때만 검색을 수행하게 한다. 그 외에 Edge ID만으로 혹은 Device ID만으로는 검색을 수행할 수 없도록 한다.

---------
위의 해결방안은 임시방편으로 실제 문제 해결을 위해서는 시간이 필요하다.

**Comment by MEC-Tracing** [comment]
추가로 Edge ID, Device ID 없이 검색을 한 경우도 위와 같은 문제가 발생한다.

이에 대한 근본적인 해결책이 필요한것으로 보인다.

**Comment by MEC-Tracing** [comment]
이에 대한 문제 해결방안으로는 보통의 User들이 복잡한 그래프의 결과를 얻었을 때, 데이터의 조건을 구체화하여 데이터에 접근하는것으로 가정한다.
